parser grammar FileScriptParser;
options { tokenVocab=FileScriptLexer; }

program: NEWLINE* stmt* EOF;

stmt: ( assign | if | while | fnCall ) ( NEWLINE+ | EOF );
assign: varname index? IS exp;
if: IF exp THEN NEWLINE+ stmt* (ELSE NEWLINE+ stmt*)? END;
while: WHILE exp DO NEWLINE+ stmt* END;
fnCall: fnName LP (args)? RP;

/* Start Code Generated by ChatGPT on 2025-01-31 */
exp: orExp;
orExp: andExp (OR andExp )*;
andExp: relExp (AND relExp )*;
relExp: addExp ( (EQ | NE | GT | LT | GE | LE) addExp )*;
addExp: mulExp ( (ADD | SUB) mulExp )*;
mulExp: baseExp ( (MUL | DIV) baseExp )*;
/* End Code Generated by ChatGPT on 2025-01-31 */

baseExp: NUM | TEXT | TRUE | FALSE | varname | fnCallExp | stack;
fnCallExp: fnCall;
args: exp (COMMA exp)*;
varname: NAME index?;
fnName: NAME;
stack: STACK;
index: LB exp RB;
